version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: calculator
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123

  nestjs-api:
    build:
      context: . 
    ports:
      - 3334:3334
    depends_on:
      - dev-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env 
